apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflowstatestore
  namespace: media-ingest
  labels:
    app.kubernetes.io/name: workflowstatestore
    app.kubernetes.io/component: dapr-state-store
    app.kubernetes.io/part-of: media-asset-ingest
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: media-ingest-postgres
        key: connection-string
    - name: tableName
      value: dapr_workflow_state
auth:
  secretStore: kubernetes
